services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: skillup_db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U ${DB_USER} -P '${DB_PASSWORD}' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    build: .
    container_name: skillup_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: skillup_db_init
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./skillup_banco/scripts/script_sistema_laboral.sql:/tmp/script.sql
    entrypoint: >
      /bin/bash -c "
      /opt/mssql-tools18/bin/sqlcmd -S db -U sa -P '${DB_PASSWORD}' -C -i /tmp/script.sql;
      echo 'Inicialização do banco concluída!';"

volumes:
  sqlserver_data: